name: new_emfor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.16.0
  provider: ^4.1.2
  flutter_google_places: ^0.2.4
  google_maps_flutter: ^0.5.26
  location: ^3.0.0
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.16
  image_picker: ^0.6.6+1
  path_provider: ^1.6.8
  intl_phone_number_input: ^0.4.4
  pin_code_fields: ^3.0.0
  shared_preferences: ^0.5.7+1
  cloud_functions: ^0.5.0
  intl: ^0.16.1
  file_picker: ^1.10.0
  firebase_storage: ^3.1.6
  http: ^0.12.1
  toast: ^0.1.5
  flutter_spinkit: ^3.1.0
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.5.0
  rating_bar: ^0.2.0
  flutter_rating_bar: ^3.0.1+1
  timeline_tile: ^0.1.2
  video_player: ^0.10.12
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.11
  progress_dialog: ^1.2.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/user_image.png
    - assets/emfor_logo.png
    - assets/marker.png
    - assets/txt.png
    - assets/doc.png
    - assets/pdf.png
    - assets/jpg.png
    - assets/tiff.png
    - assets/add_file.png
    - assets/poland_icon.png
    - assets/other_problem.png
    - assets/leak_pipe.png
    - assets/timeout.png
    - assets/dupa.mp4
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
        - asset: assets/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/Anton-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
        - asset: assets/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
        - asset: assets/Quicksand-Bold.ttf
          weight: 700
    - family: Gotham
      fonts:
        - asset: assets/GothamBook.ttf
        - asset: assets/GothamMedium.ttf
          
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
